# Aljabar Linear
Aljabar linear adalah landasan dari banyak bidang komputasi modern. Dari rendering grafika komputer hingga melatih model pembelajaran mesin yang kompleks dan menganalisis set data besar, prinsip-prinsip aljabar linear menyediakan kerangka kerja untuk merepresentasikan dan memanipulasi data dalam bentuk vektor dan matriks. Bagian ini akan mendemonstrasikan bagaimana operasi aljabar linear inti—seperti manipulasi matriks, dekomposisi, dan analisis nilai eigen—dapat diimplementasikan secara efisien dalam Python, mengubah konsep abstrak menjadi alat komputasi yang nyata.

## Matriks & Operasi Matriks
Secara teoretis, menurut `LADR4e.pdf`, matriks adalah representasi numerik dari sebuah peta linear. Jika `T` adalah peta linear dari ruang vektor `V` ke `W`, maka matriks `ℳ(T)` merepresentasikan peta ini sehubungan dengan basis yang diberikan. Entri `A_j,k` dalam matriks ini mendefinisikan bagaimana vektor basis dari `V` ditransformasikan menjadi kombinasi linear dari vektor basis di `W`. Operasi fundamental pada matriks, seperti penjumlahan dan perkalian, sesuai dengan komposisi peta linear ini.

Skrip Python berikut menggunakan library `NumPy` untuk mendemonstrasikan operasi matriks dasar.

In [1]:
import numpy as np

# Membuat dua matriks 2x3
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

# 1. Penjumlahan Matriks (elemen-per-elemen)
penjumlahan_matriks = A + B
print("Hasil Penjumlahan Matriks A + B:\n", penjumlahan_matriks)

# Membuat matriks B yang kompatibel untuk perkalian (3x2)
B_kompatibel = np.array([[7, 8],
                         [9, 10],
                         [11, 12]])

# 2. Perkalian Matriks (A @ B_kompatibel)
perkalian_matriks = A @ B_kompatibel
print("\nHasil Perkalian Matriks A @ B_kompatibel:\n", perkalian_matriks)

Hasil Penjumlahan Matriks A + B:
 [[ 8 10 12]
 [14 16 18]]

Hasil Perkalian Matriks A @ B_kompatibel:
 [[ 58  64]
 [139 154]]


**Penjelasan Kode:**

- `import numpy as np`: Mengimpor library NumPy, yang merupakan standar industri untuk komputasi numerik di Python.
- `np.array([...])`: Membuat objek `ndarray` NumPy, yang merupakan cara efisien untuk merepresentasikan matriks dan vektor.
- `A + B`: NumPy menangani penjumlahan matriks secara intuitif. Operator `+` melakukan penjumlahan elemen-per-elemen, yang hanya didefinisikan untuk matriks dengan dimensi yang sama.
- `A @ B_kompatibel`: Operator `@` (diperkenalkan di Python 3.5) digunakan secara khusus untuk perkalian matriks. Perlu diperhatikan bahwa perkalian matriks memerlukan jumlah kolom matriks pertama sama dengan jumlah baris matriks kedua. Di sini, `A` (2x3) dikalikan dengan `B_kompatibel` (3x2), menghasilkan matriks 2x2.
- Ini secara komputasi mengonfirmasi bahwa operasi `+` dan `@` di NumPy secara akurat mencerminkan konsep teoretis penjumlahan dan komposisi peta linear.

## **Skalar, Vektor, dan Tensor**

Dalam kerangka aljabar linear `LADR4e.pdf`, ruang vektor adalah himpunan `V` yang dilengkapi dengan operasi penjumlahan dan perkalian skalar.

- **Skalar**: Anggota dari suatu bidang `F` (seperti bilangan real atau kompleks) yang digunakan untuk "menskalakan" vektor. Ini adalah entitas 0-dimensi.
- **Vektor**: Elemen dari ruang vektor `V`. Biasanya direpresentasikan sebagai array angka 1-dimensi.
- **Tensor**: Generalisasi dari skalar dan vektor ke dimensi yang lebih tinggi. Matriks adalah tensor peringkat-2 (atau 2-dimensi), dan tensor dapat diperluas ke 3-dimensi atau lebih, sering digunakan dalam fisika dan pembelajaran mendalam (deep learning).

In [2]:
import numpy as np

# Mendefinisikan Skalar, Vektor, dan Tensor
skalar = 10
vektor = np.array([1, 2, 3])
matriks = np.array([[1, 2, 3], [4, 5, 6]]) # Tensor peringkat-2
tensor_3d = np.arange(24).reshape(2, 3, 4) # Tensor peringkat-3

print("Skalar:\n", skalar)
print("\nVektor (Array 1D):\n", vektor)
print("\nMatriks (Tensor Peringkat-2):\n", matriks)

# Operasi Perkalian Skalar
vektor_hasil = skalar * vektor
matriks_hasil = skalar * matriks

print("\nHasil Perkalian Skalar dengan Vektor:\n", vektor_hasil)
print("\nHasil Perkalian Skalar dengan Matriks:\n", matriks_hasil)

Skalar:
 10

Vektor (Array 1D):
 [1 2 3]

Matriks (Tensor Peringkat-2):
 [[1 2 3]
 [4 5 6]]

Hasil Perkalian Skalar dengan Vektor:
 [10 20 30]

Hasil Perkalian Skalar dengan Matriks:
 [[10 20 30]
 [40 50 60]]


**Penjelasan Kode:**

- `skalar = 10`: Variabel Python standar dapat berfungsi sebagai skalar.
- `np.array([1, 2, 3])`: Array 1D NumPy secara alami merepresentasikan vektor.
- `np.array([[...],[...]])`: Array 2D (atau lebih tinggi) NumPy merepresentasikan tensor.
- `skalar * vektor`: NumPy menyiarkan (broadcasts) operasi perkalian skalar ke setiap elemen vektor atau matriks, yang sejalan dengan definisi perkalian skalar dalam aljabar linear.
- Dengan demikian, struktur data NumPy secara langsung merepresentasikan objek-objek aljabar ini, memungkinkan kita untuk menerapkan konsep teoretis perkalian skalar secara komputasi.

## **Dekomposisi Nilai Singular (Singular Value Decomposition - SVD)**

Singular Value Decomposition (SVD) adalah faktorisasi matriks yang kuat. Berdasarkan `LADR4e.pdf` (Bagian 7.70), SVD mendekomposisi setiap peta linear `T` sehingga untuk setiap vektor `v`, `Tv` dinyatakan sebagai `𝑠₁⟨𝑣, 𝑒₁⟩𝑓₁ + ⋯ + 𝑠ₘ⟨𝑣, 𝑒ₘ⟩𝑓ₘ`. Ini merepresentasikan transformasi sebagai jumlah berbobot dari peta-peta peringkat satu, di mana bobotnya adalah nilai-nilai singular `s_k`, dan `e_k` serta `f_k` adalah vektor-vektor ortonormal.

In [3]:
import numpy as np

# Membuat matriks 2x2
A = np.array([[1, 2],
              [3, 4]])

# Melakukan SVD
U, s, Vh = np.linalg.svd(A)

print("Matriks U:\n", U)
print("\nNilai Singular (s):\n", s)
print("\nMatriks V transpose (Vh):\n", Vh)

# Memverifikasi dekomposisi A ≈ U @ S @ Vh
# s adalah vektor 1D, jadi kita perlu mengubahnya menjadi matriks diagonal
S_diag = np.diag(s)
A_rekonstruksi = U @ S_diag @ Vh

print("\nMatriks yang Direkonstruksi:\n", A_rekonstruksi)

Matriks U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Nilai Singular (s):
 [5.4649857  0.36596619]

Matriks V transpose (Vh):
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

Matriks yang Direkonstruksi:
 [[1. 2.]
 [3. 4.]]


**Penjelasan Kode:**

- `np.linalg.svd(A)`: Fungsi ini menghitung SVD dari matriks `A`.
- `**U**`: Matriks ortogonal yang kolom-kolomnya adalah vektor singular kiri (sesuai dengan `f_k` dalam teori). Ini adalah basis ortonormal untuk ruang kolom `A`.
- `**s**`: Array 1D yang berisi nilai-nilai singular dari `A`. Ini adalah bobot dalam dekomposisi.
- `**Vh**`: Transpose dari matriks ortogonal `V`, di mana kolom-kolom `V` adalah vektor singular kanan (sesuai dengan `e_k`). Ini adalah basis ortonormal untuk ruang baris `A`.
- Verifikasi numerik ini menunjukkan bagaimana dekomposisi `U, s, Vh` secara konkret merekonstruksi matriks asli, sejalan dengan dekomposisi teoretis peta linear menjadi komponen-komponen dasarnya.

## **Determinan dan Invers Matriks**

**Determinan** adalah nilai skalar yang dapat dihitung dari matriks persegi dan memberikan informasi tentang transformasi linear yang diwakilinya (misalnya, bagaimana volume berubah). Determinan nol menyiratkan bahwa matriks tersebut _singular_. **Invers matriks** (jika ada) membatalkan efek dari matriks asli. Keterbalikan (invertibility) sebuah peta linear, seperti yang dibahas dalam `LADR4e.pdf` (Bagian 3.63), setara dengan peta tersebut bersifat _injektif_ (satu-ke-satu) dan _surjektif_ (ke atas). Hanya matriks persegi yang dapat memiliki invers, dan hanya jika determinannya bukan nol.

In [4]:
import numpy as np

# Membuat matriks persegi yang dapat diinvers
A = np.array([[4, 7],
              [2, 6]])

# 1. Menghitung Determinan
det_A = np.linalg.det(A)
print(f"Determinan dari A: {det_A:.2f}")

# 2. Menghitung Invers
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInvers dari A:\n", inv_A)

    # 3. Verifikasi: A @ inv(A) harus menghasilkan matriks identitas
    identitas = A @ inv_A
    print("\nHasil A @ inv(A):\n", identitas)
    print("\nVerifikasi (apakah mendekati matriks identitas):", np.allclose(identitas, np.eye(2)))
else:
    print("\nMatriks A adalah singular dan tidak memiliki invers.")

Determinan dari A: 10.00

Invers dari A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Hasil A @ inv(A):
 [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]

Verifikasi (apakah mendekati matriks identitas): True


**Penjelasan Kode:**

- `np.linalg.det(A)`: Menghitung determinan dari matriks persegi `A`.
- `np.linalg.inv(A)`: Menghitung invers dari matriks `A`. Fungsi ini akan menghasilkan error jika matriks tersebut singular.
- `A @ inv_A`: Melakukan perkalian matriks antara `A` dan inversnya.
- `np.allclose(identitas, np.eye(2))`: Karena komputasi floating-point dapat menimbulkan kesalahan presisi kecil, kita menggunakan `np.allclose` untuk memeriksa apakah hasil `A @ inv(A)` "cukup dekat" dengan matriks identitas (`np.eye(2)`).
- Hasil ini secara numerik memvalidasi definisi teoretis dari matriks invers: sebuah transformasi yang, ketika dikomposisikan dengan matriks asli, menghasilkan transformasi identitas.

## **Nilai Eigen dan Diagonalisasi**

Menurut `LADR4e.pdf`, **nilai eigen** (`eigenvalue`) dari sebuah operator (atau matriks) `T` adalah skalar `λ` sedemikian rupa sehingga ada vektor non-nol `v` (disebut **vektor eigen** atau `eigenvector`) yang memenuhi persamaan `Tv = λv`. Secara intuitif, vektor eigen adalah arah-arah yang tidak berubah (hanya diregangkan atau dipendekkan) ketika transformasi linear `T` diterapkan. Nilai eigen yang sesuai adalah faktor peregangan tersebut.

In [5]:
import numpy as np

# Membuat matriks persegi
A = np.array([[2, 1],
              [1, 2]])

# Menghitung nilai eigen dan vektor eigen
nilai_eigen, vektor_eigen = np.linalg.eig(A)

print("Nilai Eigen (w):\n", nilai_eigen)
print("\nVektor Eigen (v):\n", vektor_eigen)

# Verifikasi untuk pasangan nilai eigen/vektor eigen pertama
w1 = nilai_eigen[0]
v1 = vektor_eigen[:, 0]

# Memeriksa apakah A @ v1 sama dengan w1 * v1
sisi_kiri = A @ v1
sisi_kanan = w1 * v1

print(f"\nVerifikasi untuk nilai eigen pertama ({w1:.2f}):")
print("A @ v1 =", sisi_kiri)
print("w1 * v1 =", sisi_kanan)
print("Apakah sama (dengan toleransi numerik):", np.allclose(sisi_kiri, sisi_kanan))

Nilai Eigen (w):
 [3. 1.]

Vektor Eigen (v):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Verifikasi untuk nilai eigen pertama (3.00):
A @ v1 = [2.12132034 2.12132034]
w1 * v1 = [2.12132034 2.12132034]
Apakah sama (dengan toleransi numerik): True


**Penjelasan Kode:**

- `np.linalg.eig(A)`: Menghitung nilai eigen dan vektor eigen dari matriks persegi `A`.
- `nilai_eigen`: Array 1D yang berisi nilai-nilai eigen (`λ`).
- `vektor_eigen`: Matriks 2D di mana setiap kolom adalah vektor eigen (`v`) yang dinormalisasi dan sesuai dengan nilai eigen pada indeks yang sama.
- Verifikasi menunjukkan bahwa menerapkan matriks `A` ke vektor eigen `v1` menghasilkan efek yang sama dengan hanya mengalikan `v1` dengan nilai eigen `w1`.
- Dengan demikian, verifikasi numerik ini secara konkret menunjukkan bahwa `vektor_eigen` adalah arah-arah yang 'istimewa' untuk matriks `A`, di mana transformasi linear direduksi menjadi operasi penskalaan sederhana oleh `nilai_eigen`, persis seperti yang dijelaskan oleh definisi teoretis `Av = λv`.

Penerapan aljabar linear dengan Python menunjukkan bagaimana abstraksi matematika yang kompleks dapat diubah menjadi operasi komputasi yang efisien. Selanjutnya, kita akan beralih ke Kalkulus, bidang matematika lain yang sangat penting untuk komputasi ilmiah.